#!/bin/sh
echo "Restart GUI after intallation..."
echo "........................."
echo "Checking for an older version in the system..."
echo "........................."
if [ -d /usr/lib/enigma2/python/Plugins/Extensions/HasBahCa ]
then
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/HasBahCa > /dev/null 2>&1
echo "An older version was found and removed"
echo "Proceeding to installation..."
else
echo "Proceeding to installation..."
fi
echo "Enjoy - Reboot system Necessary!..."
exit 0
