#!/bin/sh

# **************************************
# HasBahCa Pre-installation Script
# **************************************

echo "========================================"
echo "HasBahCa Pre-installation Script"
echo "========================================"

# Main plugin directory
EXTDIR="/usr/lib/enigma2/python/Plugins/Extensions/HasBahCa"
if [ -d "$EXTDIR" ]; then
    echo "Removing: $EXTDIR"
    rm -rf "$EXTDIR" > /dev/null 2>&1
fi


echo "========================================"
echo "Pre-installation cleanup complete!"
echo "Ready for new installation."
echo "========================================"

exit 0
